{{- if .Values.agents.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "panhandler.fullname" . }}-agents
  labels:
    {{- include "panhandler.labels" . | nindent 4 }}
    app.kubernetes.io/component: agents
spec:
  {{- if not .Values.agents.autoscaling.enabled }}
  replicas: {{ .Values.agents.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "panhandler.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: agents
  template:
    metadata:
      labels:
        {{- include "panhandler.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: agents
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "panhandler.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: agents
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.agents.image.registry }}/{{ .Values.agents.image.repository }}:{{ .Values.agents.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.agents.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.agents.service.targetPort }}
              protocol: TCP
          env:
            {{- toYaml .Values.agents.env | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.agents.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }} 