{{- if .Values.agents.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "panhandler.fullname" . }}-agents
  labels:
    {{- include "panhandler.labels" . | nindent 4 }}
    app.kubernetes.io/component: agents
spec:
  type: {{ .Values.agents.service.type }}
  ports:
    - port: {{ .Values.agents.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "panhandler.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: agents
---
{{- end }}
{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "panhandler.fullname" . }}-web
  labels:
    {{- include "panhandler.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "panhandler.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
{{- end }} 